# Generated by Django 5.1 on 2024-08-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='creator',
            new_name='producer',
        ),
    ]
