# Generated by Django 5.1 on 2024-08-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='anime',
            name='producer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='anime',
            name='release_date',
            field=models.DateField(),
        ),
    ]
